global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "extractor"
    static_configs:
      - targets: ["extractor:8000"]

  - job_name: "transformer"
    static_configs:
      - targets: ["transformer:8000"]

  - job_name: "cleaner"
    static_configs:
      - targets: ["cleaner:8000"]
      
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
      
  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:9000']
      
  - job_name: "streamlit"
    static_configs:
      - targets: ["app:8000"]
      
rule_files:
  - alerts.yml
